### ISSUE TITLE
IA6

### ISSUE THREAD

**Issue by csranasinghe** [codezilla2018/ideapool#1]
In this project is it a standalone desktop app or a web app? Can we use any technology?

**Comment by tharindu99** [comment]
This would be working as library, But I prefer to introduce that as middleware(middle layer application). There are a lot of good chart libraries and when we pass json object with given standard it will generate proper graphical visualizations. [C3.js](http://c3js.org/samples/chart_bar.html).
```
var chart = c3.generate({
    data: {
        columns: [
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 130, 100, 140, 200, 150, 50]
        ],
        type: 'bar'
    },
    bar: {
        width: {
            ratio: 0.5 // this makes bar width 50% of length between ticks
        }
        // or
        //width: 100 // this makes bar width 100px
    }
});
```
But this is not meaningful for non-technical users. If we can propose more suitable grammar closely similar to a logical natural language and that can generate this json object. That would be awesome.
Technically it would be more useful if you can implement this based on js. (as a js library). That library get string as an input and return this kind of standard json output. JS based implementation may allows to run your code every where( web / standalone/mobile), So that would be an added advantage and it will make you comfortable to convert that json object to a graph more easily. 
Please let me know if you have any confusions or need any further clarifications.

**Comment by csranasinghe** [comment]
Thank you for your reply.
